# Generated by Django 4.2.3 on 2023-08-03 16:04

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('program', models.CharField(choices=[('Bachelor of Laws', 'Bachelor of Laws'), ('Diploma in Paralegal Studies', 'Diploma in Paralegal Studies'), ('Diploma in Law', 'Diploma in Law'), ('Bachelor of Science in Economics', 'Bachelor of Science in Economics'), ('Bachelor of Science in Agriculture Economics', 'Bachelor of Science in Agriculture Economics'), ('Bachelor of Science in Agribusiness', 'Bachelor of Science in Agribusiness'), ('Bachelor of Arts in Environment and Development Studies', 'Bachelor of Arts in Environment and Development Studies'), ('Bachelor of Arts in Communication Studies', 'Bachelor of Arts in Communication Studies'), ('Bachelor of Arts in Theology', 'Bachelor of Arts in Theology'), ('Bachelor of Science in Psychology', 'Bachelor of Science in Psychology'), ('Bachelor of Arts in Sociology', 'Bachelor of Arts in Sociology'), ('Bachelor of Arts in Social Work', 'Bachelor of Arts in Social Work'), ('Bachelor of Arts in French', 'Bachelor of Arts in French'), ('Bachelor of Science in Management Studies', 'Bachelor of Science in Management Studies'), ('Bachelor of Science in Banking and Finance', 'Bachelor of Science in Banking and Finance'), ('Bachelor of Science in Business Administration', 'Bachelor of Science in Business Administration'), ('Doctor of Pharmacy', 'Doctor of Pharmacy'), ('Bachelor of Architecture', 'Bachelor of Architecture'), ('Bachelor of Science in Planning', 'Bachelor of Science in Planning'), ('Bachelor of Science in Real Estate', 'Bachelor of Science in Real Estate'), ('Bachelor of Science in Graphic Design', 'Bachelor of Science in Graphic Design'), ('Bachelor of Science in Fashion Design', 'Bachelor of Science in Fashion Design'), ('Bachelor of Science in Landscape Design', 'Bachelor of Science in Landscape Design'), ('Bachelor of Science in Interior Design', 'Bachelor of Science in Interior Design'), ('Bachelor of Science in Computer Science', 'Bachelor of Science in Computer Science'), ('Bachelor of Science in Civil Engineering', 'Bachelor of Science in Civil Engineering'), ('Bachelor of Science in Information Technology', 'Bachelor of Science in Information Technology'), ('Bachelor of Science in Environmental Engineering', 'Bachelor of Science in Environmental Engineering'), ('Bachelor of Science in Nursing', 'Bachelor of Science in Nursing'), ('Bachelor of Science in Physician Assistantship', 'Bachelor of Science in Physician Assistantship'), ('Bachelor of Science in Public Health', 'Bachelor of Science in Public Health')], max_length=255)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(default=0)),
                ('gpa', models.FloatField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=255)),
                ('credit_hour', models.IntegerField(default=0)),
                ('grade', models.CharField(choices=[('4', 'A'), ('3.5', 'B+'), ('3', 'B'), ('2.5', 'C+'), ('2', 'C'), ('1.5', 'D+'), ('1', 'D'), ('0', 'F')], max_length=15)),
                ('grade_point', models.FloatField(default=0)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
