# Generated by Django 4.2.3 on 2023-08-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='resit',
            field=models.BooleanField(default=True),
        ),
    ]
